services:
  app:
    image: ghcr.io/arge2004/schedule-generator-udea:latest
    container_name: schedule-generator
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network
    mem_limit: 400m

networks:
  app-network:
    driver: bridge